name: Java CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Compile with Maven (or javac)
        run: |
          mkdir bin
          javac -d bin src/com/mycompany/chatapp/*.java

      - name: Run Tests (optional if you added test classes)
        run: echo "No unit tests found, skipping for now"
